### ISSUE TITLE
Problem when using example from device-sdk-go in docker-compose file

### ISSUE THREAD

**Issue by tntthanh** [edgexfoundry/device-sdk-go#1205] opened 2022-08-09 08:34 UTC
Hi everyone,
I had built the example of device-sdk-go, had run locally perfectly via make-build execute file, and then pushed it to my docker hub, using it in my docker-compose file, along with other edgex-compose services (e.g: edgex-core-data, edgex-core-metadata,...). I had add "device-simple" into variables: ADD_KNOWN_SECRETS and ADD_SECRETSTORE_TOKENS in secretstore-setup. But, I got this error running the example service with the following log of the errors, please help me solve this:

"...
edgex-device-simple       | /edgex-init/ready_to_run_wait_install.sh: exec: line 41: /device-simple: not found
edgex-device-simple       | Tue Aug  9 08:16:58 UTC 2022 Starting /device-simple -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res ...
edgex-device-simple exited with code 127
..."

**Comment by lenny-intel** [comment] 2022-08-09 15:33
This is a question for the UI
Closing as this is a duplicate of https://github.com/edgexfoundry/edgex-ui-go/issues/546

**Comment by lenny-intel** [comment] 2022-08-10 15:15
Opps, sorry. was on a different issue, but commented and closed this one.. reopened

**Comment by lenny-intel** [comment] 2022-08-10 15:19
You are missing the `entrypoint` and `cmd` property overrides like are here: 
https://github.com/edgexfoundry/edgex-compose/blob/main/docker-compose.yml#L386-L394

Is there a reason you are doing this with security enabled?

**Comment by lenny-intel** [comment] 2022-08-10 15:29
closing again now that it is a duplicate

**Closed** 2022-11-30 02:30 UTC
Labels: duplicate
