### ISSUE TITLE
404 - Item not found\n" error: Couldn't register to metadata service

### ISSUE THREAD

**Issue by wassim6975** [edgexfoundry/device-sdk-go#370] opened 2019-09-17 13:11 UTC
Hello everyone, 
I was creating a device-simple with this tutorial https://docs.edgexfoundry.org/Ch-GettingStartedSDK-Go.html but I have a problem when I want to run my device-simple. 

MacBook-Air-de-wassim:device-simple wassim$ ./device-simple
Init: useRegistry:  profile:  confDir: 
Loading configuration from: /Users/wassim/go/src/github.com/edgexfoundry/device-simple/cmd/device-simple/res/configuration.toml

Bypassing registration in registry...
Calling service.Start.
EnableRemote is false, using local log file
level=INFO ts=2019-09-17T13:04:18.73519Z app=device-simple source=init.go:137 msg="Check Data service's status ..."
level=INFO ts=2019-09-17T13:04:18.735196Z app=device-simple source=init.go:137 msg="Check Metadata service's status ..."
level=INFO ts=2019-09-17T13:04:18.7492Z app=device-simple source=init.go:47 msg="Service clients initialize successful."
level=ERROR ts=2019-09-17T13:04:18.770807Z app=device-simple source=service.go:145 msg="DeviceServicForName failed: 404 - Item not found\n"
error: Couldn't register to metadata service

Can someone help me to solve this problem please ? 

Thank you :)

**Comment by kranthisai** [comment] 2019-09-20 17:11
Same issue

**Comment by cloudxxx8** [comment] 2019-09-21 04:04
@wassim6975 and @kranthisai 
I can reproduce this issue now, and it is caused by the change of go-mod-core-contracts
The easy to make it work is keep our existing go module setting.  It works fine with v0.1.16, and we haven't updated it.  Please make sure the definition in your go.mod is as follows
`github.com/edgexfoundry/go-mod-core-contracts v0.1.16`

If you are not using go module, please checkout the v0.1.16 tag in your local go-mod-core-contracts repository
`git checkout v0.1.16`

**Comment by cloudxxx8** [comment] 2019-10-18 08:44
fixed by #375

**Closed by cloudxxx8** 2019-10-18 08:44 UTC
